[phases.setup]
nixpkgs = ['nodejs_20', 'python3']
aptPkgs = ['git', 'ca-certificates', 'curl']

[phases.install]
cmds = [
    'npm install -g pnpm@10.16.1',
    'pnpm install --frozen-lockfile --ignore-scripts'
]

[phases.build]
cmds = [
    'pnpm build:deploy'
]

[start]
cmd = 'pnpm start:railway'

[variables]
NODE_ENV = 'production'
N8N_HOST = '0.0.0.0'
N8N_PORT = '$PORT'
N8N_PROTOCOL = 'https'
WEBHOOK_URL = 'https://$RAILWAY_STATIC_URL/'

# Prevent Railway from detecting other services
[nixpacks]
name = "n8n"