[build]
builder = "nixpacks"
buildCommand = "pnpm install --frozen-lockfile && pnpm build:deploy"

[deploy]
startCommand = "pnpm start:railway"
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "never"

[variables]
NODE_ENV = "production"
N8N_HOST = "0.0.0.0"
N8N_PORT = "$PORT"
N8N_PROTOCOL = "https"
WEBHOOK_URL = "https://$RAILWAY_STATIC_URL/"